isaac/urls.py
from django.conf.urls import url
from . import views


app_name = 'isaac'

urlpatterns = [
    url(r'^register',views.register, name='register'),
]

projectsix/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from isaac import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^isaac',include('isaac.urls',namespace='isaac')),
    url(r'^$',views.home, name='home'),
    url(r'^login',views.login, name='login'),
    url(r'^logout',views.logout, name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

isaac/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfile(models.Model):
    # create the rship with the User model DO NOT INHERIT
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # additional attributes
    picture = models.ImageField(upload_to='profile_pics')
    portfolio = models.URLField(blank=True)

    def __str__(self):
        return self.user.username

isaac/forms.py
from django import forms
from isaac.models import UserProfile, User


#user fields
class Userbase(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password']


#extra fields
class UserForm(forms.ModelForm):
    picture = forms.ImageField(required=False)
    class Meta:
        model = UserProfile
        fields = ['portfolio','picture']

isaac/views.py
from django.shortcuts import render
from .forms import User, UserForm, Userbase
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def home(request):
    return render(request, 'home.html')

# @login_required
# def logout(request):
#     logout(request)
#     return HttpResponseRedirect(reverse('home'))


def register(request):
    registered = False
    if request.method == 'POST':
        # get info from both forms
        user_form = Userbase(data=request.POST)
        profile_form = UserForm(data=request.POST)

        # check if forms are valid
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            # hash password
            user.set_password(user.password)
            user.save()

            # deal with the custom fields
            profile = profile_form.save(commit=False)
            # sets one to one rship btn UserBase and Userform
            profile.user = user

            # manipulation
            if 'picture' in request.FILES:
                # stores the image in the media file FILES contains a dictionary of media DIRS
                # same thing is done for files
                profile.picture = request.FILES['profile_pics']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    # if it was not HTTP post, render the forms as blanks
    else:
        user_form = Userbase()
        profile_form = UserForm()
    return render(request, 'signup.html', {'user_form': user_form, 'profile_form': profile_form})

@login_required
def logout(request):
    logout(request)
    return render(request,'home.html')


def login(request):
    if request.method == 'POST':
        # grabbing the fields
        username = request.POST.get('username')
        password = request.POST.get('password')

        # authenticate
        user = authenticate(username=username, password=password)
        # if user is in db
        if user:
            if user.is_active():
                login(request,user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse('Your account is not active')
        else:
            return HttpResponse('Invalod login details')
    else:
        return render(request, 'login.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Base{% endblock %}</title>
</head>
<body>
<nav>
    <ul>
        <li><a href="{% url 'home'%}">Home</a></li> {# index #}
        <li><a href="{% url 'admin:index' %}">Admin</a></li> {# Admin #}
        <li><a href="{% url 'isaac:register'%}">Sign up</a></li> {# Register #}
    </ul>
</nav>

{#check if user is auhenticated#}
{% if user.is_authenticated %}
    <a href="{% url 'logout'%}">Logout</a>
    {% else %}
    <a href="{% url 'login'%}">Login</a>
{% endif %}


<div>
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
    <div>
        <h1>Django User Authentication Class</h1>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
    <div>
        <h1>Django User Authentication Class</h1>
        <div>
            <h2>Please Login</h2>
            <form action="" method="post">
                {% csrf_token %}
                <label for="username">UerName</label>
                <input type="text" placeholder="username" id="username" name="username"><br>
                <label for="password">Password</label>
                <input type="password" placeholder="********" id="password" name="password"><br>
                <input type="submit" name="Log in">
            </form>
        </div>
    </div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% block title %}Sign up{% endblock %}

{% block content %}
    <div>
        {% if registered %}
            <h1>Thank you for registering </h1>
        {% else %}
                <h2>Register here</h2>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" value="Register">
            </form>
        {% endif %}
    </div>
{% endblock %}